### ISSUE TITLE
[Docker] Script not running due to tkinter problem at Matplotlib

### ISSUE THREAD

**Issue by injelee** [injelee/melanoma_backend#11]
This one is strange - when we just had Suyash's repo in it's pure form, main.py worked like a charm and http://0.0.0.0:8000/ would yield 'hello world'. Now, I'm getting the following from our server.py file, when running the same GET command for hello world:

server_1   | 172.19.0.1 - - [12/Dec/2017 01:21:28] "GET / HTTP/1.1" 500 -
server_1   | Traceback (most recent call last):
server_1   |   File "/notebooks/main.py", line 2, in <module>
server_1   |     from find_melanoma import Melanoma
server_1   |   File "/notebooks/find_melanoma.py", line 3, in <module>
server_1   |     import matplotlib.pyplot as plt
server_1   |   File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 113, in <module>
server_1   |     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
server_1   |   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
server_1   |     [backend_name], 0)
server_1   |   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
server_1   |     from six.moves import tkinter as Tk
server_1   |   File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
server_1   |     mod = mod._resolve()
server_1   |   File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
server_1   |     return _import_module(self.mod)
server_1   |   File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
server_1   |     __import__(name)
server_1   |   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
server_1   |     raise ImportError, str(msg) + ', please install the python-tk package'
server_1   | ImportError: No module named _tkinter, please install the python-tk package

I don't know why it's looking into usr/lib/python2.7 in the first place, since I know that my computer has tkinter and _tkinter with some code I used from stackoverflow.  Any pointers?

**Comment by ad12** [comment]
Hey @injelee tried the fix discussed yesterday?

**Comment by injelee** [comment]
So I was able to fix the 404 error by getting rid of the non-functional flask script.  Now that there's one script that has our functional flask apps in them, we don't get the 404 error; instead, we have this really strange error when trying to run our basic hello_world app.  I don't understand why it's bringing up stuff in main.py that we're not calling, but even so, I don't understand the error itself.  Is tkinter something that needs to be specified in some virenv or in the Docker container? I thought tkinter was ubiquitous and should be installed already?

**Comment by injelee** [comment]
Please help! Can't process our test image without overcoming this error.

**Comment by jl3392** [comment]
I tried to clone the repo on my laptop and ran it. I have the same error return.

**Comment by suyashkumar** [comment]
@injelee give @Ouwen's PR a try see if it works

**Comment by jl3392** [comment]
I tried, but still have ImportError as follows:
ImportError: No module named _tkinter, please install the python-tk package @suyashkumar @Ouwen

**Comment by Ouwen** [comment]
i'm cloning your master branch now, going in.

**Comment by Ouwen** [comment]
Alright, so if you add those two lines into your dockerfile then run:

`docker-compose up --build`

you should be able to get the `hello world2`

**Comment by jl3392** [comment]
Thank you so much!!! @Ouwen

**Comment by injelee** [comment]
Thank you very much @Ouwen, you are a hero.
